/**
 * Freak In The Sheets - Referral Listings
 * UK-based premium adult store accepting crypto (BTC, ETH)
 * Real products scraped from freakinthesheets.co.uk
 */

import { Listing } from '../types';
import clitoralSquirrelImg from '@/assets/freakinthesheets/clitoral-squirrel.jpg';
import paddlePinkImg from '@/assets/freakinthesheets/paddle-pink.jpg';
import buttPlugBlingImg from '@/assets/freakinthesheets/butt-plug-bling.jpg';
import nippleClampsImg from '@/assets/freakinthesheets/nipple-clamps.jpg';
import miniRabbitImg from '@/assets/freakinthesheets/mini-rabbit.jpg';
import rabbitVibratorImg from '@/assets/freakinthesheets/rabbit-vibrator.jpg';
import teddyRedImg from '@/assets/freakinthesheets/teddy-red.jpg';
import laceBodysuitImg from '@/assets/freakinthesheets/lace-bodysuit.jpg';
import collarBlackImg from '@/assets/freakinthesheets/collar-black.jpg';
import lipstickVibeImg from '@/assets/freakinthesheets/lipstick-vibe.jpg';

const FREAK_BASE_URL = 'https://freakinthesheets.co.uk';

const getProductUrl = (slug: string) => {
  return `${FREAK_BASE_URL}/product/${slug}/`;
};

export const freakInTheSheetsListings: Partial<Listing>[] = [
  {
    id: 'fits-clitoral-001',
    title: 'Clitoral Squirrel Sucking GVibe',
    description: 'Advanced clitoral suction device with multiple intensity modes. Rechargeable, waterproof design. Discreet and powerful.',
    priceUsd: 38.09,
    priceXmr: 0.23,
    category: 'adult-intimacy',
    images: [clitoralSquirrelImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('clitoral-squirrel-sucking-gvibe'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-paddle-001',
    title: 'Rouge Garments Paddle Pink',
    description: 'Premium pink leather paddle for sensual play. Durable construction with comfortable grip handle. Perfect for beginners and experienced users.',
    priceUsd: 31.74,
    priceXmr: 0.19,
    category: 'adult-intimacy',
    images: [paddlePinkImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('rouge-garments-paddle-pink'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-plug-001',
    title: 'Anal Adventures Matrix Swirling Bling Butt Plug',
    description: 'Luxurious butt plug with sparkling crystal jewel accent. Smooth silicone design for comfortable wear. Body-safe materials.',
    priceUsd: 26.63,
    priceXmr: 0.16,
    category: 'adult-intimacy',
    images: [buttPlugBlingImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('anal-adventures-matrix-swirling-bling-butt-plug'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-clamps-001',
    title: 'Black Nipple Clamps',
    description: 'Adjustable nipple clamps with connecting chain. Metal construction for durability. Suitable for all experience levels.',
    priceUsd: 35.54,
    priceXmr: 0.21,
    category: 'adult-intimacy',
    images: [nippleClampsImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('black-nipple-clamps'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-mini-rabbit-001',
    title: 'Nude Hazel Mini Rabbit Massager',
    description: 'Compact dual-stimulation rabbit vibrator in elegant nude tone. Multiple vibration modes, USB rechargeable, whisper-quiet motor.',
    priceUsd: 44.44,
    priceXmr: 0.27,
    category: 'adult-intimacy',
    images: [miniRabbitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('nude-hazel-mini-rabbit-massager'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-flutter-001',
    title: 'Rocks Off Flutter Rabbit Pink',
    description: 'Premium dual-stimulation rabbit vibrator with fluttering action. Powerful motors, fully waterproof, USB rechargeable.',
    priceUsd: 59.67,
    priceXmr: 0.36,
    category: 'adult-intimacy',
    images: [rabbitVibratorImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('rocks-off-flutter-rabbit-pink'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-teddy-001',
    title: 'Le Desir Crotchless Rhinestone Teddy Red',
    description: 'Glamorous red teddy with rhinestone detailing. Crotchless design, adjustable straps. Available in plus sizes UK 14-20.',
    priceUsd: 24.13,
    priceXmr: 0.15,
    category: 'adult-intimacy',
    images: [teddyRedImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('le-desir-crotchless-rhinestone-teddy-red-uk-14-to-20'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-bodystocking-001',
    title: 'Le Desir Suspender Bodystocking',
    description: 'Elegant black bodystocking with suspender design. Stretchy comfortable fit. Plus size friendly UK 14-20.',
    priceUsd: 22.85,
    priceXmr: 0.14,
    category: 'adult-intimacy',
    images: [laceBodysuitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('le-desir-suspender-bodystocking-uk-14-to-20'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-collar-001',
    title: 'Rouge Garments O-Ring Thin Studded Collar Black',
    description: 'Stylish black leather collar with O-ring and studded detailing. Adjustable fit, durable construction. Perfect for bondage play.',
    priceUsd: 30.47,
    priceXmr: 0.18,
    category: 'adult-intimacy',
    images: [collarBlackImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('rouge-garments-oring-thin-studded-collar-black'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-lipstick-001',
    title: 'Naughty Bits Bad Bitch Rechargeable Lipstick Vibrator',
    description: 'Discreet lipstick-style vibrator in elegant case. USB rechargeable, travel-friendly, powerful yet whisper-quiet. Perfect for on-the-go pleasure.',
    priceUsd: 35.54,
    priceXmr: 0.21,
    category: 'adult-intimacy',
    images: [lipstickVibeImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('naughty-bits-bad-bitch-rechargeable-lipstick-vibrator'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
];

export const freakInTheSheetsSeller = {
  id: 'freak-in-the-sheets',
  displayName: 'Freak In The Sheets',
  bio: 'UK-based premium adult store. High quality products. Accepts BTC, ETH. Discreet shipping.',
  location: 'United Kingdom',
  partnerUrl: FREAK_BASE_URL,
  acceptsCrypto: ['BTC', 'ETH'],
};
