/**
 * Freak In The Sheets - Referral Listings
 * UK-based premium adult store accepting crypto (BTC, ETH)
 * Real products scraped from freakinthesheets.co.uk
 */

import { Listing } from '../types';

// Image imports - Real products only
import rabbitVibratorImg from '@/assets/freakinthesheets/rabbit-vibrator.jpg';
import spreaderBarImg from '@/assets/freakinthesheets/spreader-bar.jpg';
import bondageKitImg from '@/assets/freakinthesheets/bondage-kit.jpg';
import paddlePinkImg from '@/assets/freakinthesheets/paddle-pink.jpg';
import pingPongPaddleImg from '@/assets/freakinthesheets/ping-pong-paddle.jpg';
import nippleClampsImg from '@/assets/freakinthesheets/nipple-clamps.jpg';
import suspenderBeltImg from '@/assets/freakinthesheets/suspender-belt.jpg';

const FREAK_BASE_URL = 'https://freakinthesheets.co.uk';

export const freakInTheSheetsListings: Partial<Listing>[] = [
  {
    id: 'fits-rabbit-vibrator',
    title: 'Rabbit Vibrator With Thrusting Motion Purple',
    description: 'Perfectly designed to reach further, this thrusting rabbit vibrator can push a further 1.5-2 inches, working the G-spot into a frenzy. There are also beads that rotate in the shaft for added sensations.',
    priceUsd: 38.99,
    priceXmr: 0.185,
    category: 'adult-intimacy',
    images: [rabbitVibratorImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: `${FREAK_BASE_URL}/product/rabbit-vibrator-with-thrusting-motion-purple/`,
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-spreader-bar',
    title: 'Ouch Adjustable Spreader Bar',
    description: "Would you like to take control during your BDSM play? This Adjustable Spreader Bar offers a variety of exciting options for couples to play. As an adjustable spreader, it allows you to customize the width between arms or legs according to your preference, providing unrestricted access to the body's most intimate areas.",
    priceUsd: 32.99,
    priceXmr: 0.157,
    category: 'adult-intimacy',
    images: [spreaderBarImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: `${FREAK_BASE_URL}/product/ouch-adjustable-spreader-bar/`,
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-bondage-harness',
    title: 'Taboom Bondage in Luxury Harness and Cuffs',
    description: 'Indulge in allure with the TABOOM Luxury Harness with Cuffs. Crafted from faux leather with gleaming gold accents and adjustable straps, it effortlessly amplifies your sensuality. Each time you slip it on, it entices attention, encouraging you to embrace your irresistible charm and craft unforgettable moments.',
    priceUsd: 50.79,
    priceXmr: 0.242,
    category: 'adult-intimacy',
    images: [bondageKitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: `${FREAK_BASE_URL}/product/taboom-bondage-in-luxury-harness-and-cuffs-small-to-med/`,
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-paddle-plug',
    title: 'Taboom Silicone Paddle and Plug',
    description: 'Double the fun with the TABOOM Silicone Paddle and Plug! Featuring a butterfly-shaped paddle with a heart detail and an anal plug handle, this indulgent duo is perfect for your naughtiest nights. Master the art of domination with satisfying taps of the paddle, combining punishment and pleasure seamlessly.',
    priceUsd: 24.11,
    priceXmr: 0.115,
    category: 'adult-intimacy',
    images: [paddlePinkImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: `${FREAK_BASE_URL}/product/taboom-silicone-paddle-and-plug/`,
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-ping-pong-paddle',
    title: 'Rouge Leather Padded Ping Pong Paddle',
    description: 'This ping-pong-style paddle has two sides, the padded side will deliver a hard whack and the other a satisfying sting. Perfect for BDSM enthusiasts looking to explore impact play.',
    priceUsd: 41.89,
    priceXmr: 0.199,
    category: 'adult-intimacy',
    images: [pingPongPaddleImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: `${FREAK_BASE_URL}/product/rouge-leather-padded-ping-pong-paddle/`,
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-nipple-clamps',
    title: 'Sex and Mischief Verge Nipple Clamps',
    description: 'Unleash your imagination and explore your desires with the Verge Nipple Clamps. Designed to engage your senses, the adjustable clamps provide just the right amount of pressure to stimulate your erogenous zones, creating an electrifying experience that will leave you craving for more.',
    priceUsd: 36.79,
    priceXmr: 0.175,
    category: 'adult-intimacy',
    images: [nippleClampsImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: `${FREAK_BASE_URL}/product/sex-and-mischief-verge-nipple-clamps/`,
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-suspender-belt',
    title: 'Cottelli Strappy Suspender Belt',
    description: '(S)extravagant style! This black suspender belt from Cottelli LINGERIE shows off the waist, hips and thighs in an exciting way! Made from soft, silky, shiny stretch straps and silver-coloured connecting rings. The suspender straps at the front and back and the double thigh straps can be adjusted to fit.',
    priceUsd: 21.57,
    priceXmr: 0.103,
    category: 'adult-intimacy',
    images: [suspenderBeltImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: `${FREAK_BASE_URL}/product/cottelli-strappy-suspender-belt/`,
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
];

export const freakInTheSheetsSeller = {
  id: 'freak-in-the-sheets',
  displayName: 'Freak In The Sheets',
  bio: 'UK-based premium adult store. High quality products. Accepts BTC, ETH. Discreet shipping.',
  location: 'United Kingdom',
  partnerUrl: FREAK_BASE_URL,
  acceptsCrypto: ['BTC', 'ETH'],
};
