/**
 * Peptides UK - Research Peptide Listings
 * UK-based research peptide vendor accepting Bitcoin
 * Established 2012 | >98% purity | cGMP ISO9001 compliant
 * 
 * DISCLAIMER: All products sold for research purposes only.
 * Not for human consumption.
 */

import { Listing } from '../types';

const PEPTIDES_UK_BASE_URL = 'https://peptidesuk.com';

// GBP to USD conversion rate
const GBP_TO_USD = 1.27;
const gbpToUsd = (gbp: number): number => Math.round(gbp * GBP_TO_USD * 100) / 100;

export const peptidesUKPartnerListings: Partial<Listing>[] = [
  // === RECOVERY PEPTIDES ===
  {
    id: 'puk-rec-001',
    title: 'BPC-157 5mg - Research Peptide',
    description: 'Body Protection Compound-157. Research peptide for tissue repair studies. >98% purity, HPLC verified. Includes bacteriostatic water and research guide. For research purposes only.',
    priceUsd: gbpToUsd(15.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/bpc-157-5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption. Consult appropriate regulatory authorities in your jurisdiction.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-rec-002',
    title: 'TB-500 5mg - Research Peptide',
    description: 'Thymosin Beta-4 fragment for recovery research. Premium grade >98% purity with MS-UPLC analysis. Popular for tissue repair and injury recovery studies.',
    priceUsd: gbpToUsd(19.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/tb-500-5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-rec-003',
    title: 'TB-500 2mg - Research Peptide',
    description: 'Thymosin Beta-4 in smaller research dose. Same premium quality, perfect for initial studies or dosage experimentation.',
    priceUsd: gbpToUsd(12.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/tb-500-2mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },

  // === GROWTH HORMONE PEPTIDES ===
  {
    id: 'puk-gh-001',
    title: 'Ipamorelin 2mg - Growth Hormone Research',
    description: 'Selective growth hormone secretagogue for research. Mild and well-studied GH peptide. >98% purity with full HPLC analysis.',
    priceUsd: gbpToUsd(14.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/ipamorelin-2mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-gh-002',
    title: 'GHRP-6 5mg - Growth Hormone Research',
    description: 'Growth Hormone Releasing Peptide-6 for appetite and GH studies. Popular research compound with extensive scientific literature.',
    priceUsd: gbpToUsd(15.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/ghrp-6-5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-gh-003',
    title: 'CJC-1295 (no DAC) 2mg - Research Peptide',
    description: 'Growth Hormone Releasing Hormone analog for research. Modified GRF version without Drug Affinity Complex. Premium quality with COA.',
    priceUsd: gbpToUsd(16.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/cjc-1295-no-dac-2mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },

  // === COGNITIVE PEPTIDES ===
  {
    id: 'puk-cog-001',
    title: 'Selank 5mg - Cognitive Research Peptide',
    description: 'Synthetic peptide derived from tuftsin for anxiolytic and nootropic research. Extensively studied Russian peptide. >98% purity.',
    priceUsd: gbpToUsd(24.95),
    category: 'health-wellness',
    subcategory: 'nootropics-cognitive',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/selank-5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-cog-002',
    title: 'Semax 5mg - Cognitive Research Peptide',
    description: 'Synthetic ACTH analog for cognitive enhancement research. Popular nootropic peptide with neuroprotective properties in studies.',
    priceUsd: gbpToUsd(29.95),
    category: 'health-wellness',
    subcategory: 'nootropics-cognitive',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/semax-5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },

  // === LONGEVITY & ANTI-AGING ===
  {
    id: 'puk-long-001',
    title: 'Epithalon 10mg - Longevity Research Peptide',
    description: 'Epitalon/Epithalamin for longevity and telomerase research. Russian peptide studied for anti-aging properties. Premium grade synthesis.',
    priceUsd: gbpToUsd(34.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/epithalon-10mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-long-002',
    title: 'GHK-Cu 50mg - Copper Peptide Research',
    description: 'Glycyl-L-Histidyl-L-Lysine copper complex for skin and wound healing research. Popular in anti-aging studies. High purity synthesis.',
    priceUsd: gbpToUsd(29.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/ghk-cu-50mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },

  // === SEXUAL HEALTH & OTHER ===
  {
    id: 'puk-sex-001',
    title: 'PT-141 10mg - Sexual Health Research',
    description: 'Bremelanotide for sexual arousal research. Melanocortin receptor agonist studied for libido effects in both sexes. >98% purity.',
    priceUsd: gbpToUsd(34.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/pt-141-10mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-tan-001',
    title: 'Melanotan II 10mg - Melanocortin Research',
    description: 'Alpha-MSH analog for melanogenesis research. Studied for tanning and appetite effects. Premium synthesis with HPLC verification.',
    priceUsd: gbpToUsd(24.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/melanotan-2-10mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },

  // === STACKS & SUPPLIES ===
  {
    id: 'puk-stack-001',
    title: 'BPC-157 + TB-500 Blend 10mg - Recovery Stack',
    description: 'Combined recovery peptide blend for comprehensive tissue repair research. 5mg BPC-157 + 5mg TB-500. Popular research combination.',
    priceUsd: gbpToUsd(29.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/bpc-157-tb-500-blend`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-sup-001',
    title: 'Bacteriostatic Water 10ml - Research Supplies',
    description: 'Pharmaceutical grade bacteriostatic water for peptide reconstitution. 0.9% benzyl alcohol. Sterile and sealed.',
    priceUsd: gbpToUsd(4.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(2.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/bacteriostatic-water`,
    ageRestricted: false,
    disclaimer: 'For research use only.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
];

// Seller profile
export const peptidesUKSeller = {
  id: 'peptides-uk',
  displayName: 'Peptides UK',
  bio: 'UK-based research peptide supplier since 2012. >98% purity guaranteed. cGMP & ISO9001 compliant laboratory. HPLC and MS-UPLC testing. Accepts Bitcoin and bank transfer. All products for research purposes only.',
  location: 'United Kingdom',
  partnerUrl: PEPTIDES_UK_BASE_URL,
  acceptsCrypto: ['BTC'],
  rating: 4.9,
  reviewCount: 131,
  isVerified: true,
  established: '2012',
};

export const getPeptidesUKListings = () => peptidesUKPartnerListings;
export const isPeptidesUKListing = (listing: Partial<Listing>) => 
  listing.sellerId === 'peptides-uk';
