/**
 * UK-Peptides - Research Peptide Listings
 * UK-based research peptide vendor accepting Bitcoin
 * Established 2012 | 99.8% purity | Europe's largest peptide stockist
 * 
 * DISCLAIMER: All products sold for research purposes only.
 * Not for human consumption.
 */

import { Listing } from '../types';

const UK_PEPTIDES_BASE_URL = 'https://uk-peptides.com';

// GBP to USD conversion rate
const GBP_TO_USD = 1.27;
const gbpToUsd = (gbp: number): number => Math.round(gbp * GBP_TO_USD * 100) / 100;

export const ukPeptidesPartnerListings: Partial<Listing>[] = [
  // === RECOVERY PEPTIDES ===
  {
    id: 'ukp-rec-001',
    title: 'BPC-157 5mg - Premium Research Peptide',
    description: 'Body Protection Compound for tissue repair research. 99.8% purity with third-party verification. Industrial-grade freezer storage. Next-day UK delivery.',
    priceUsd: gbpToUsd(16.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/bpc-157-5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption. Consult appropriate regulatory authorities in your jurisdiction.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ukp-rec-002',
    title: 'TB-500 5mg - Research Grade',
    description: 'Thymosin Beta-4 for advanced recovery studies. 99.8% purity, batch tested. Popular for tissue regeneration and injury recovery research.',
    priceUsd: gbpToUsd(19.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/tb-500-5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ukp-rec-003',
    title: 'TB-500 2mg - Research Peptide',
    description: 'Thymosin Beta-4 in smaller research dose. Same premium 99.8% purity. Perfect for initial studies or dose-response experiments.',
    priceUsd: gbpToUsd(11.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/tb-500-2mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },

  // === GROWTH HORMONE PEPTIDES ===
  {
    id: 'ukp-gh-001',
    title: 'CJC-1295 (no DAC) 2mg - GH Research',
    description: 'Modified GRF(1-29) for growth hormone research. Premium synthesis without Drug Affinity Complex. 99.8% purity verified.',
    priceUsd: gbpToUsd(14.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/cjc-1295-no-dac-2mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ukp-gh-002',
    title: 'CJC-1295 (no DAC) 5mg - GH Research',
    description: 'Larger vial for extended research projects. Same premium Modified GRF quality. Industrial storage ensures integrity.',
    priceUsd: gbpToUsd(24.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/cjc-1295-no-dac-5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ukp-gh-003',
    title: 'Ipamorelin 2mg - Selective GH Secretagogue',
    description: 'Growth hormone secretagogue for research. Mild and selective peptide with extensive literature. 99.8% purity guaranteed.',
    priceUsd: gbpToUsd(12.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/ipamorelin-2mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ukp-gh-004',
    title: 'GHRP-6 5mg - Growth Hormone Research',
    description: 'Growth Hormone Releasing Peptide-6 for appetite and GH studies. Well-documented research compound. Premium synthesis.',
    priceUsd: gbpToUsd(14.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/ghrp-6-5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ukp-gh-005',
    title: 'GHRP-2 5mg - Growth Hormone Research',
    description: 'Growth Hormone Releasing Peptide-2 for GH secretion studies. More potent than GHRP-6. Laboratory grade purity.',
    priceUsd: gbpToUsd(14.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/ghrp-2-5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ukp-gh-006',
    title: 'Hexarelin 2mg - Potent GH Research',
    description: 'Powerful growth hormone secretagogue for advanced research. Synthetic hexapeptide. 99.8% purity with COA.',
    priceUsd: gbpToUsd(13.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/hexarelin-2mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },

  // === COGNITIVE PEPTIDES ===
  {
    id: 'ukp-cog-001',
    title: 'Selank 5mg - Nootropic Research Peptide',
    description: 'Russian nootropic peptide for anxiolytic and cognitive research. Synthetic tuftsin analog. Extensively studied compound.',
    priceUsd: gbpToUsd(22.95),
    category: 'health-wellness',
    subcategory: 'nootropics-cognitive',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/selank-5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },

  // === LONGEVITY & SPECIALIZED ===
  {
    id: 'ukp-long-001',
    title: 'Epithalon 10mg - Longevity Research',
    description: 'Epitalon peptide for telomerase and longevity research. Russian anti-aging compound. 99.8% purity pharmaceutical grade.',
    priceUsd: gbpToUsd(29.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/epithalon-10mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ukp-vasc-001',
    title: 'Vesugen 10mg - Vascular Research Peptide',
    description: 'Bioregulator peptide for vascular system research. Part of Khavinson peptide series. European pharmaceutical grade.',
    priceUsd: gbpToUsd(34.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/vesugen-10mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },

  // === METABOLIC RESEARCH ===
  {
    id: 'ukp-met-001',
    title: 'AOD-9604 2mg - Metabolic Research',
    description: 'Anti-Obesity Drug fragment for metabolic and fat loss research. Modified HGH fragment. Premium synthesis quality.',
    priceUsd: gbpToUsd(18.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/aod-9604-2mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ukp-met-002',
    title: 'HGH Fragment 176-191 2mg - Fat Loss Research',
    description: 'Modified amino acid sequence from HGH for lipolysis research. Popular metabolic research peptide. 99.8% purity.',
    priceUsd: gbpToUsd(16.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/hgh-fragment-176-191-2mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },

  // === SEXUAL HEALTH ===
  {
    id: 'ukp-sex-001',
    title: 'PT-141 10mg - Sexual Arousal Research',
    description: 'Bremelanotide for libido and sexual arousal research. Melanocortin receptor agonist. Studied in both male and female research.',
    priceUsd: gbpToUsd(32.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/pt-141-10mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },

  // === BUNDLES & BULK ===
  {
    id: 'ukp-bulk-001',
    title: 'BPC-157 Bundle 5x5mg - Bulk Research Pack',
    description: 'Five vials of BPC-157 5mg at discounted bulk pricing. Perfect for long-term studies. All individually sealed with COA.',
    priceUsd: gbpToUsd(84.75),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/bpc-157-bundle-5x5mg`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ukp-combo-001',
    title: 'TB-500 + BPC-157 Combo Pack',
    description: 'Popular recovery stack. Includes 1x TB-500 5mg + 1x BPC-157 5mg. Save versus buying separately. Premium quality both peptides.',
    priceUsd: gbpToUsd(34.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/tb-500-bpc-157-combo`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },

  // === RESEARCH SUPPLIES ===
  {
    id: 'ukp-sup-001',
    title: 'Bacteriostatic Water 10ml - Sterile',
    description: 'Pharmaceutical grade bacteriostatic water for peptide reconstitution. 0.9% benzyl alcohol preservative. Sterile sealed vial.',
    priceUsd: gbpToUsd(4.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(2.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/bacteriostatic-water-10ml`,
    ageRestricted: false,
    disclaimer: 'For research use only.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ukp-sup-002',
    title: 'Acetic Acid 0.6% 10ml - Research Grade',
    description: 'Dilute acetic acid solution for specialized peptide reconstitution. Required for certain peptides like Fragment 176-191. Pharmaceutical grade.',
    priceUsd: gbpToUsd(3.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: ['/placeholder.svg'],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(2.95),
    fulfillment: 'referral',
    referralUrl: `${UK_PEPTIDES_BASE_URL}/acetic-acid-solution`,
    ageRestricted: false,
    disclaimer: 'For research use only.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    sellerId: 'uk-peptides',
    createdAt: new Date().toISOString(),
  },
];

// Seller profile
export const ukPeptidesSeller = {
  id: 'uk-peptides',
  displayName: 'UK-Peptides',
  bio: "Europe's largest peptide stockist since 2012. 99.8% purity guaranteed. Industrial-grade freezer storage. Next-day UK delivery. Accepts Bitcoin, bank transfer, and card. All products for research purposes only.",
  location: 'United Kingdom',
  partnerUrl: UK_PEPTIDES_BASE_URL,
  acceptsCrypto: ['BTC'],
  rating: 4.9,
  reviewCount: 500,
  isVerified: true,
  established: '2012',
};

export const getUKPeptidesListings = () => ukPeptidesPartnerListings;
export const isUKPeptidesListing = (listing: Partial<Listing>) => 
  listing.sellerId === 'uk-peptides';
